replicaCount: 1

image:
  repository: spike-me
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: spike-me.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

resources: {}

nodeSelector: {}

tolerations: {}

affinity: {}

healthCheck:
  enabled: false
