apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    prometheus: prometheus
    role: alert-rules
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: 'slack-notifications'
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 3h
    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - send_resolved: true
            api_url: 'https://hooks.slack.com/services/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'
            channel: '#your-channel'
            text: "{{ range .Alerts }}\n *Alert:* {{ .Annotations.summary }}\n *Description:* {{ .Annotations.description }}\n *Severity:* {{ .Labels.severity }}\n *Status:* {{ .Status }}\n *Start:* {{ .StartsAt }}\n *End:* {{ .EndsAt }}\n{{ end }}"

