apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  labels:
    app: prometheus
data:
  spike-me-alerts.yaml: |
    groups:
    - name: spike-me-alerts
      rules:
      - alert: HighLatency
        expr: histogram_quantile(0.9, rate(http_request_duration_seconds_bucket[1m])) > 0.3
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "90th percentile latency is above 300ms for the last minute"
      - alert: HighCpuLoad
        expr: rate(container_cpu_usage_seconds_total[1m]) > 0.8
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU load detected"
          description: "CPU load is above 80% for the last minute"
  test-alert.yaml: |
    groups:
    - name: test-alerts
      rules:
      - alert: TestAlert
        expr: vector(1)
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "This is a test alert"
          description: "This alert is to test the alerting setup"

