apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: spike-me-alerts
  labels:
    prometheus: prometheus
    role: alert-rules
spec:
  groups:
    - name: spike-me-alerts
      rules:
        - alert: HighLatency
          expr: histogram_quantile(0.9, rate(prometheus_http_request_duration_seconds_bucket[1m])) > 0.3
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "High latency detected"
            description: "90th percentile latency is above 300ms for the last minute"
        - alert: HighCpuLoad
          expr: rate(container_cpu_usage_seconds_total[1m]) > 0.8
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "High CPU load detected"
            description: "CPU load is above 80% for the last minute"

