apiVersion: v1
kind: Service
metadata:
  name: spike-me
  labels:
    app: spike-me
spec:
  type: NodePort
  selector:
    app: spike-me
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP

